# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: mnist-app
  labels:
    # label your deployment
    app: mnist-app
spec:
  # The number of pods/replicas to run
  replicas: 1            
  selector:
    matchLabels:
    # selector to match the pod
      app: mnist-app
  template:
    metadata:
      labels:
      # label your pod
        app: mnist-app
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: mnist-app
      # Add the local image name
        image: mnist-app:new
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 3000   
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: mnist-app-svc
spec:
  selector:
    # selector that matches the pod
    app: mnist-app
  # type of service
  type: LoadBalancer     
  ports:
  - protocol: TCP 
    # port for exposing the service        
    port: 5000
    # port for exposing the pod             
    targetPort: 3000
    # port for exposing the node       
    nodePort: 31110